version: 0.2

env:
  variables:
    S3_BUCKET: "felipegilo-pipeline"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm ci || npm install

  build:
    commands:
      - echo "Running React build..."
      - npm run build
      - echo "Build completed."

  post_build:
    commands:
      - echo "Deploying build folder to S3..."
      - aws s3 cp ./build $S3_BUCKET --recursive --acl public-read
      - echo "✅ Deployment to S3 completed successfully."

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
