version: 0.2

phases:
  install:
    commands:
      # Exemplo para um projeto Node.js
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      # ESTA LINHA CRIA OS ARTEFATOS NO DIRETÓRIO ./build
      - echo Running build command...
      - npm run build 
      # Se for um projeto React, Next.js, ou Vue, este comando 
      # geralmente gera o diretório 'build' ou 'dist'.
      
  post_build:
    commands:
      # ESTA LINHA TENTA COPIAR O DIRETÓRIO GERADO
      - echo Deploying to S3...
      - aws s3 cp ./build $S3_BUCKET --recursive
      
artifacts:
  # É uma boa prática listar o diretório de build como artefato
  files:
    - '**/*'
  base-directory: 'build'
